### ISSUE TITLE
What is label_cap.txt?

### ISSUE THREAD

**Issue by Matthew-Lyu** [982999184/MOF#1]
Dear author, thank you for your code, it is very good. I have a small question, where is the label_cap.txt in line 29 of train.py?
<img width="663" alt="image" src="https://github.com/982999184/MOF/assets/113096109/31f95b5a-da6c-4e61-ba50-2d6877ff0ebc">

**Comment by 982999184** [comment]
The "label_cap.txt" in the code is the label corresponding to the dataset, because this file is part of the dataset, and the dataset is too large to be uploaded, so it is not uploaded in this code. However, I have uploaded it to make it easier for you to understand the code. This code was written in a hurry and may not be easy to understand, if you have other questions, please continue to communicate!

**Comment by Matthew-Lyu** [comment]
I downloaded the dataset, and only the train_npy file generated after I ran CIF_to_npy.py was 30GB. What is the format of the label_cap.txt file you mentioned?
https://1drv.ms/u/s!AtuVqcWZi8aAy11S2wxataTe8IMH

**Comment by 982999184** [comment]
"label.txt" is a file created by myself for the convenience of the code to store labels, the size of N × 2, N is the number of structures, each line is the name of the structure and its corresponding performance, separated by commas, and its data from the data set. This file I have updated and uploaded in the project.

**Comment by Matthew-Lyu** [comment]
OK, thank you. Best wishes.
