### ISSUE TITLE
label_sel.txt File Missing?

### ISSUE THREAD

**Issue by fork123aniket** [982999184/MOF#2]
Hi,

I really find this implementation quite awesome and helpful. Thank you for hosting this on GitHub.

However, I think the performance (CO2 selectivity labels) file is missing from this repo. Could you please guide me to where to find the labels for CO2 selectivity, as you've made CO2 capacity labels available (label_cap.txt) in your repo?

Thank you. Looking forward to your reply...

**Comment by 982999184** [comment]
Hi, I'm sorry for the confusion, I was actually going to add the CO2 selectivity together when I last added the tags, but at that time the file was lost due to a computer change. But since you raised the issue I tried to find the file and it has now been supplemented, if you have any other questions you can ask me.

**Comment by fork123aniket** [comment]
This resolved my issue. Thank you!
